#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd "$(dirname "$0")" && pwd)"
source "$script_dir/lib.sh"

run_scenario_test lib identity_collision
run_scenario_test lib contract_file_publish_no_overwrite_destination_already_exists
run_scenario_test lib contract_file_publish_different_destination_returns_typed_collision
run_scenario_test lib different_byte_destination_race_keeps_loser_failed_without_metadata_write
run_scenario_test lib planner_rebinds_nonregular_expected_path_after_collision_planning
run_scenario_test lib live_photo_motion_with_size_suffixed_primary_stem_is_on_disk_skipped
run_scenario_test lib live_photo_direct_motion_identity_with_untracked_regular_base_is_on_disk_skipped
run_scenario_test lib live_photo_direct_motion_identity_with_symlink_base_fails_without_download_or_ordinal
run_scenario_test lib live_photo_motion_with_identity_suffixed_primary_stem_is_on_disk_skipped
run_scenario_test lib live_photo_motion_with_sanitized_identity_suffix_is_on_disk_skipped
run_scenario_test lib live_photo_motion_original_policy_with_primary_collision_is_on_disk_skipped
run_scenario_test lib live_photo_motion_collision_family_requires_regular_base_not_state_owner
run_scenario_test lib full_streaming_video_only_uses_state_proven_collision_primary
run_scenario_test lib incremental_collecting_new_live_photo_motion_uses_state_proven_bare_primary
run_scenario_test lib pending_retry_new_live_photo_motion_uses_state_proven_bare_primary
run_scenario_test lib cleanup_retry_replanning_matches_state_proven_live_photo_motion_path
run_scenario_test lib import_matches_live_photo_motion_from_size_suffixed_primary_stem
run_scenario_test lib import_matches_live_photo_motion_from_sanitized_identity_suffixed_primary_stem
run_scenario_test lib pending_same_size_collision_does_not_adopt_other_assets_bare_file
run_scenario_test lib truncated_suffixed_downloaded_file_is_forwarded_not_on_disk_skipped
run_scenario_test lib path_reconciliation_copies_catalog_file_without_provider_inventory
run_scenario_test lib path_reconciliation_preserves_source_sidecar_custom_xmp_and_layers_provider_fields
run_scenario_test lib path_reconciliation_creates_missing_configured_sidecar
run_scenario_test lib path_reconciliation_retries_after_sidecar_write_and_state_failure
run_scenario_test lib path_reconciliation_conflicting_destination_sidecar_keeps_old_state
run_scenario_test lib path_reconciliation_destination_media_replacement_keeps_old_state
run_scenario_test lib path_reconciliation_no_metadata_moves_only_media_and_mtime
run_scenario_test lib path_reconciliation_keeps_owned_identity_collision_path
run_scenario_test lib path_reconciliation_changed_provider_version_requeues_without_copy
run_scenario_test lib path_reconciliation_motion_identity_requires_regular_base
run_scenario_test lib download_config_v3_hash_stages_reconciliation
run_scenario_test lib run_cycle_v3_hash_print_only_preserves_path_state
run_scenario_test lib download_config_v2_hash_without_live_photo_video_migrates_directly
run_scenario_test lib download_config_v2_hash_with_live_photo_video_stages_reconciliation
run_scenario_test lib downloaded_live_photo_video_query_only_counts_downloaded_motion_rows
run_scenario_test lib run_cycle_download_config_hash_drift_keeps_source_incremental
run_scenario_test lib local_reconciliation_copy_rejects_non_regular_paths
run_scenario_test lib download_config_revert_restages_active_reconciliation
run_scenario_test lib legacy_download_config_revert_restages_active_reconciliation
run_scenario_test lib reconciliation_reservations_separate_same_size_assets
run_scenario_test lib reconciliation_version_config_preserves_raw_policy
run_scenario_test lib scoped_download_config_hash_changes_with_selection
